[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
syntax = { path = "../syntax/" }
clap = { version = "4.2.4", features = ["derive"] }
eyre = "0.6.8"
lsp-server = "0.7.0"
lsp-types = "0.94.0"
serde_json = "1.0.96"
